#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Innovation")]
	public partial class LogDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRequest(Request instance);
    partial void UpdateRequest(Request instance);
    partial void DeleteRequest(Request instance);
    partial void InsertQueryTime(QueryTime instance);
    partial void UpdateQueryTime(QueryTime instance);
    partial void DeleteQueryTime(QueryTime instance);
    partial void InsertBugReport(BugReport instance);
    partial void UpdateBugReport(BugReport instance);
    partial void DeleteBugReport(BugReport instance);
    partial void InsertPersonLog(PersonLog instance);
    partial void UpdatePersonLog(PersonLog instance);
    partial void DeletePersonLog(PersonLog instance);
    partial void InsertLog(Log instance);
    partial void UpdateLog(Log instance);
    partial void DeleteLog(Log instance);
    partial void InsertAdminChange(AdminChange instance);
    partial void UpdateAdminChange(AdminChange instance);
    partial void DeleteAdminChange(AdminChange instance);
    #endregion
		
		public LogDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["InnovationConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LogDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LogDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LogDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LogDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Request> Requests
		{
			get
			{
				return this.GetTable<Request>();
			}
		}
		
		public System.Data.Linq.Table<QueryTime> QueryTimes
		{
			get
			{
				return this.GetTable<QueryTime>();
			}
		}
		
		public System.Data.Linq.Table<BugReport> BugReports
		{
			get
			{
				return this.GetTable<BugReport>();
			}
		}
		
		public System.Data.Linq.Table<PersonLog> PersonLogs
		{
			get
			{
				return this.GetTable<PersonLog>();
			}
		}
		
		public System.Data.Linq.Table<Log> Logs
		{
			get
			{
				return this.GetTable<Log>();
			}
		}
		
		public System.Data.Linq.Table<AdminChange> AdminChanges
		{
			get
			{
				return this.GetTable<AdminChange>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Requests")]
	public partial class Request : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Request1;
		
		private string _ID;
		
		private System.DateTime _Time;
		
		private EntityRef<Log> _Log;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRequest1Changing(string value);
    partial void OnRequest1Changed();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnTimeChanging(System.DateTime value);
    partial void OnTimeChanged();
    #endregion
		
		public Request()
		{
			this._Log = default(EntityRef<Log>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Request", Storage="_Request1", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Request1
		{
			get
			{
				return this._Request1;
			}
			set
			{
				if ((this._Request1 != value))
				{
					this.OnRequest1Changing(value);
					this.SendPropertyChanging();
					this._Request1 = value;
					this.SendPropertyChanged("Request1");
					this.OnRequest1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					if (this._Log.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Log_Request", Storage="_Log", ThisKey="ID", OtherKey="ID", IsForeignKey=true)]
		public Log Log
		{
			get
			{
				return this._Log.Entity;
			}
			set
			{
				Log previousValue = this._Log.Entity;
				if (((previousValue != value) 
							|| (this._Log.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Log.Entity = null;
						previousValue.Requests.Remove(this);
					}
					this._Log.Entity = value;
					if ((value != null))
					{
						value.Requests.Add(this);
						this._ID = value.ID;
					}
					else
					{
						this._ID = default(string);
					}
					this.SendPropertyChanged("Log");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QueryTimes")]
	public partial class QueryTime : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private double _Elapsed;
		
		private string _Query;
		
		private System.DateTime _Now;
		
		private bool _ShowAll;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnElapsedChanging(double value);
    partial void OnElapsedChanged();
    partial void OnQueryChanging(string value);
    partial void OnQueryChanged();
    partial void OnNowChanging(System.DateTime value);
    partial void OnNowChanged();
    partial void OnShowAllChanging(bool value);
    partial void OnShowAllChanged();
    #endregion
		
		public QueryTime()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Elapsed", DbType="Float NOT NULL", IsPrimaryKey=true)]
		public double Elapsed
		{
			get
			{
				return this._Elapsed;
			}
			set
			{
				if ((this._Elapsed != value))
				{
					this.OnElapsedChanging(value);
					this.SendPropertyChanging();
					this._Elapsed = value;
					this.SendPropertyChanged("Elapsed");
					this.OnElapsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Query", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Query
		{
			get
			{
				return this._Query;
			}
			set
			{
				if ((this._Query != value))
				{
					this.OnQueryChanging(value);
					this.SendPropertyChanging();
					this._Query = value;
					this.SendPropertyChanged("Query");
					this.OnQueryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Now", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Now
		{
			get
			{
				return this._Now;
			}
			set
			{
				if ((this._Now != value))
				{
					this.OnNowChanging(value);
					this.SendPropertyChanging();
					this._Now = value;
					this.SendPropertyChanged("Now");
					this.OnNowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowAll", DbType="Bit NOT NULL")]
		public bool ShowAll
		{
			get
			{
				return this._ShowAll;
			}
			set
			{
				if ((this._ShowAll != value))
				{
					this.OnShowAllChanging(value);
					this.SendPropertyChanging();
					this._ShowAll = value;
					this.SendPropertyChanged("ShowAll");
					this.OnShowAllChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BugReports")]
	public partial class BugReport : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Report;
		
		private string _ReporterMisparIshi;
		
		private System.DateTime _TimeReported;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReportChanging(string value);
    partial void OnReportChanged();
    partial void OnReporterMisparIshiChanging(string value);
    partial void OnReporterMisparIshiChanged();
    partial void OnTimeReportedChanging(System.DateTime value);
    partial void OnTimeReportedChanged();
    #endregion
		
		public BugReport()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Report", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Report
		{
			get
			{
				return this._Report;
			}
			set
			{
				if ((this._Report != value))
				{
					this.OnReportChanging(value);
					this.SendPropertyChanging();
					this._Report = value;
					this.SendPropertyChanged("Report");
					this.OnReportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReporterMisparIshi", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ReporterMisparIshi
		{
			get
			{
				return this._ReporterMisparIshi;
			}
			set
			{
				if ((this._ReporterMisparIshi != value))
				{
					this.OnReporterMisparIshiChanging(value);
					this.SendPropertyChanging();
					this._ReporterMisparIshi = value;
					this.SendPropertyChanged("ReporterMisparIshi");
					this.OnReporterMisparIshiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeReported", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime TimeReported
		{
			get
			{
				return this._TimeReported;
			}
			set
			{
				if ((this._TimeReported != value))
				{
					this.OnTimeReportedChanging(value);
					this.SendPropertyChanging();
					this._TimeReported = value;
					this.SendPropertyChanged("TimeReported");
					this.OnTimeReportedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Persons")]
	public partial class PersonLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MisparIshi;
		
		private string _WorkPhone;
		
		private string _GivenName;
		
		private string _JobTitle;
		
		private string _Location;
		
		private string _LongWorkTitle;
		
		private string _AlternateName;
		
		private string _Department;
		
		private string _Company;
		
		private string _Mobile;
		
		private string _Mail;
		
		private System.Data.Linq.Binary _Picture;
		
		private string _Surname;
		
		private string _Darga;
		
		private string _Sex;
		
		private string _BirthdayDisplayString;
		
		private string _JobTitleSearchable;
		
		private string _LongWorkTitleSearchable;
		
		private string _AlternateNameSearchable;
		
		private string _DepartmentSearchable;
		
		private string _CompanySearchable;
		
		private long _Tags;
		
		private string _OtherTelephone;
		
		private string _Fax;
		
		private string _HomeTelephone;
		
		private string _WhatIDo;
		
		private System.Nullable<bool> _MobilePhoneIsManuallyInput;
		
		private System.Nullable<bool> _WorkPhoneIsManuallyInput;
		
		private System.Nullable<bool> _OtherPhoneIsManuallyInput;
		
		private System.Nullable<bool> _SexIsManuallyInput;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMisparIshiChanging(string value);
    partial void OnMisparIshiChanged();
    partial void OnWorkPhoneChanging(string value);
    partial void OnWorkPhoneChanged();
    partial void OnGivenNameChanging(string value);
    partial void OnGivenNameChanged();
    partial void OnJobTitleChanging(string value);
    partial void OnJobTitleChanged();
    partial void OnLocationChanging(string value);
    partial void OnLocationChanged();
    partial void OnLongWorkTitleChanging(string value);
    partial void OnLongWorkTitleChanged();
    partial void OnAlternateNameChanging(string value);
    partial void OnAlternateNameChanged();
    partial void OnDepartmentChanging(string value);
    partial void OnDepartmentChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnMobileChanging(string value);
    partial void OnMobileChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnPictureChanging(System.Data.Linq.Binary value);
    partial void OnPictureChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnDargaChanging(string value);
    partial void OnDargaChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnBirthdayDisplayStringChanging(string value);
    partial void OnBirthdayDisplayStringChanged();
    partial void OnJobTitleSearchableChanging(string value);
    partial void OnJobTitleSearchableChanged();
    partial void OnLongWorkTitleSearchableChanging(string value);
    partial void OnLongWorkTitleSearchableChanged();
    partial void OnAlternateNameSearchableChanging(string value);
    partial void OnAlternateNameSearchableChanged();
    partial void OnDepartmentSearchableChanging(string value);
    partial void OnDepartmentSearchableChanged();
    partial void OnCompanySearchableChanging(string value);
    partial void OnCompanySearchableChanged();
    partial void OnTagsChanging(long value);
    partial void OnTagsChanged();
    partial void OnOtherTelephoneChanging(string value);
    partial void OnOtherTelephoneChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnHomeTelephoneChanging(string value);
    partial void OnHomeTelephoneChanged();
    partial void OnWhatIDoChanging(string value);
    partial void OnWhatIDoChanged();
    partial void OnMobilePhoneIsManuallyInputChanging(System.Nullable<bool> value);
    partial void OnMobilePhoneIsManuallyInputChanged();
    partial void OnWorkPhoneIsManuallyInputChanging(System.Nullable<bool> value);
    partial void OnWorkPhoneIsManuallyInputChanged();
    partial void OnOtherPhoneIsManuallyInputChanging(System.Nullable<bool> value);
    partial void OnOtherPhoneIsManuallyInputChanged();
    partial void OnSexIsManuallyInputChanging(System.Nullable<bool> value);
    partial void OnSexIsManuallyInputChanged();
    #endregion
		
		public PersonLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MisparIshi", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MisparIshi
		{
			get
			{
				return this._MisparIshi;
			}
			set
			{
				if ((this._MisparIshi != value))
				{
					this.OnMisparIshiChanging(value);
					this.SendPropertyChanging();
					this._MisparIshi = value;
					this.SendPropertyChanged("MisparIshi");
					this.OnMisparIshiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkPhone", DbType="VarChar(255)")]
		public string WorkPhone
		{
			get
			{
				return this._WorkPhone;
			}
			set
			{
				if ((this._WorkPhone != value))
				{
					this.OnWorkPhoneChanging(value);
					this.SendPropertyChanging();
					this._WorkPhone = value;
					this.SendPropertyChanged("WorkPhone");
					this.OnWorkPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string GivenName
		{
			get
			{
				return this._GivenName;
			}
			set
			{
				if ((this._GivenName != value))
				{
					this.OnGivenNameChanging(value);
					this.SendPropertyChanging();
					this._GivenName = value;
					this.SendPropertyChanged("GivenName");
					this.OnGivenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitle", DbType="VarChar(255)")]
		public string JobTitle
		{
			get
			{
				return this._JobTitle;
			}
			set
			{
				if ((this._JobTitle != value))
				{
					this.OnJobTitleChanging(value);
					this.SendPropertyChanging();
					this._JobTitle = value;
					this.SendPropertyChanged("JobTitle");
					this.OnJobTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Location", DbType="VarChar(255)")]
		public string Location
		{
			get
			{
				return this._Location;
			}
			set
			{
				if ((this._Location != value))
				{
					this.OnLocationChanging(value);
					this.SendPropertyChanging();
					this._Location = value;
					this.SendPropertyChanged("Location");
					this.OnLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongWorkTitle", DbType="VarChar(255)")]
		public string LongWorkTitle
		{
			get
			{
				return this._LongWorkTitle;
			}
			set
			{
				if ((this._LongWorkTitle != value))
				{
					this.OnLongWorkTitleChanging(value);
					this.SendPropertyChanging();
					this._LongWorkTitle = value;
					this.SendPropertyChanged("LongWorkTitle");
					this.OnLongWorkTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlternateName", DbType="VarChar(255)")]
		public string AlternateName
		{
			get
			{
				return this._AlternateName;
			}
			set
			{
				if ((this._AlternateName != value))
				{
					this.OnAlternateNameChanging(value);
					this.SendPropertyChanging();
					this._AlternateName = value;
					this.SendPropertyChanged("AlternateName");
					this.OnAlternateNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Department", DbType="VarChar(255)")]
		public string Department
		{
			get
			{
				return this._Department;
			}
			set
			{
				if ((this._Department != value))
				{
					this.OnDepartmentChanging(value);
					this.SendPropertyChanging();
					this._Department = value;
					this.SendPropertyChanged("Department");
					this.OnDepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company", DbType="VarChar(255)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="VarChar(255)")]
		public string Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="VarChar(255)")]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Picture", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Picture
		{
			get
			{
				return this._Picture;
			}
			set
			{
				if ((this._Picture != value))
				{
					this.OnPictureChanging(value);
					this.SendPropertyChanging();
					this._Picture = value;
					this.SendPropertyChanged("Picture");
					this.OnPictureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(255)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Darga", DbType="VarChar(255)")]
		public string Darga
		{
			get
			{
				return this._Darga;
			}
			set
			{
				if ((this._Darga != value))
				{
					this.OnDargaChanging(value);
					this.SendPropertyChanging();
					this._Darga = value;
					this.SendPropertyChanged("Darga");
					this.OnDargaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="VarChar(255)")]
		public string Sex
		{
			get
			{
				return this._Sex;
			}
			set
			{
				if ((this._Sex != value))
				{
					this.OnSexChanging(value);
					this.SendPropertyChanging();
					this._Sex = value;
					this.SendPropertyChanged("Sex");
					this.OnSexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BirthdayDisplayString", DbType="VarChar(5)")]
		public string BirthdayDisplayString
		{
			get
			{
				return this._BirthdayDisplayString;
			}
			set
			{
				if ((this._BirthdayDisplayString != value))
				{
					this.OnBirthdayDisplayStringChanging(value);
					this.SendPropertyChanging();
					this._BirthdayDisplayString = value;
					this.SendPropertyChanged("BirthdayDisplayString");
					this.OnBirthdayDisplayStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JobTitleSearchable", DbType="VarChar(255)")]
		public string JobTitleSearchable
		{
			get
			{
				return this._JobTitleSearchable;
			}
			set
			{
				if ((this._JobTitleSearchable != value))
				{
					this.OnJobTitleSearchableChanging(value);
					this.SendPropertyChanging();
					this._JobTitleSearchable = value;
					this.SendPropertyChanged("JobTitleSearchable");
					this.OnJobTitleSearchableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongWorkTitleSearchable", DbType="VarChar(255)")]
		public string LongWorkTitleSearchable
		{
			get
			{
				return this._LongWorkTitleSearchable;
			}
			set
			{
				if ((this._LongWorkTitleSearchable != value))
				{
					this.OnLongWorkTitleSearchableChanging(value);
					this.SendPropertyChanging();
					this._LongWorkTitleSearchable = value;
					this.SendPropertyChanged("LongWorkTitleSearchable");
					this.OnLongWorkTitleSearchableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlternateNameSearchable", DbType="VarChar(255)")]
		public string AlternateNameSearchable
		{
			get
			{
				return this._AlternateNameSearchable;
			}
			set
			{
				if ((this._AlternateNameSearchable != value))
				{
					this.OnAlternateNameSearchableChanging(value);
					this.SendPropertyChanging();
					this._AlternateNameSearchable = value;
					this.SendPropertyChanged("AlternateNameSearchable");
					this.OnAlternateNameSearchableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DepartmentSearchable", DbType="VarChar(255)")]
		public string DepartmentSearchable
		{
			get
			{
				return this._DepartmentSearchable;
			}
			set
			{
				if ((this._DepartmentSearchable != value))
				{
					this.OnDepartmentSearchableChanging(value);
					this.SendPropertyChanging();
					this._DepartmentSearchable = value;
					this.SendPropertyChanged("DepartmentSearchable");
					this.OnDepartmentSearchableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanySearchable", DbType="VarChar(255)")]
		public string CompanySearchable
		{
			get
			{
				return this._CompanySearchable;
			}
			set
			{
				if ((this._CompanySearchable != value))
				{
					this.OnCompanySearchableChanging(value);
					this.SendPropertyChanging();
					this._CompanySearchable = value;
					this.SendPropertyChanged("CompanySearchable");
					this.OnCompanySearchableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tags", DbType="BigInt NOT NULL")]
		public long Tags
		{
			get
			{
				return this._Tags;
			}
			set
			{
				if ((this._Tags != value))
				{
					this.OnTagsChanging(value);
					this.SendPropertyChanging();
					this._Tags = value;
					this.SendPropertyChanged("Tags");
					this.OnTagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherTelephone", DbType="VarChar(255)")]
		public string OtherTelephone
		{
			get
			{
				return this._OtherTelephone;
			}
			set
			{
				if ((this._OtherTelephone != value))
				{
					this.OnOtherTelephoneChanging(value);
					this.SendPropertyChanging();
					this._OtherTelephone = value;
					this.SendPropertyChanged("OtherTelephone");
					this.OnOtherTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(255)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeTelephone", DbType="VarChar(255)")]
		public string HomeTelephone
		{
			get
			{
				return this._HomeTelephone;
			}
			set
			{
				if ((this._HomeTelephone != value))
				{
					this.OnHomeTelephoneChanging(value);
					this.SendPropertyChanging();
					this._HomeTelephone = value;
					this.SendPropertyChanged("HomeTelephone");
					this.OnHomeTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhatIDo", DbType="VarChar(255)")]
		public string WhatIDo
		{
			get
			{
				return this._WhatIDo;
			}
			set
			{
				if ((this._WhatIDo != value))
				{
					this.OnWhatIDoChanging(value);
					this.SendPropertyChanging();
					this._WhatIDo = value;
					this.SendPropertyChanged("WhatIDo");
					this.OnWhatIDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobilePhoneIsManuallyInput", DbType="Bit")]
		public System.Nullable<bool> MobilePhoneIsManuallyInput
		{
			get
			{
				return this._MobilePhoneIsManuallyInput;
			}
			set
			{
				if ((this._MobilePhoneIsManuallyInput != value))
				{
					this.OnMobilePhoneIsManuallyInputChanging(value);
					this.SendPropertyChanging();
					this._MobilePhoneIsManuallyInput = value;
					this.SendPropertyChanged("MobilePhoneIsManuallyInput");
					this.OnMobilePhoneIsManuallyInputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkPhoneIsManuallyInput", DbType="Bit")]
		public System.Nullable<bool> WorkPhoneIsManuallyInput
		{
			get
			{
				return this._WorkPhoneIsManuallyInput;
			}
			set
			{
				if ((this._WorkPhoneIsManuallyInput != value))
				{
					this.OnWorkPhoneIsManuallyInputChanging(value);
					this.SendPropertyChanging();
					this._WorkPhoneIsManuallyInput = value;
					this.SendPropertyChanged("WorkPhoneIsManuallyInput");
					this.OnWorkPhoneIsManuallyInputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OtherPhoneIsManuallyInput", DbType="Bit")]
		public System.Nullable<bool> OtherPhoneIsManuallyInput
		{
			get
			{
				return this._OtherPhoneIsManuallyInput;
			}
			set
			{
				if ((this._OtherPhoneIsManuallyInput != value))
				{
					this.OnOtherPhoneIsManuallyInputChanging(value);
					this.SendPropertyChanging();
					this._OtherPhoneIsManuallyInput = value;
					this.SendPropertyChanged("OtherPhoneIsManuallyInput");
					this.OnOtherPhoneIsManuallyInputChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SexIsManuallyInput", DbType="Bit")]
		public System.Nullable<bool> SexIsManuallyInput
		{
			get
			{
				return this._SexIsManuallyInput;
			}
			set
			{
				if ((this._SexIsManuallyInput != value))
				{
					this.OnSexIsManuallyInputChanging(value);
					this.SendPropertyChanging();
					this._SexIsManuallyInput = value;
					this.SendPropertyChanged("SexIsManuallyInput");
					this.OnSexIsManuallyInputChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Logs")]
	public partial class Log : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID;
		
		private System.Nullable<int> _RequestsMade;
		
		private System.Nullable<int> _MailSent;
		
		private System.Nullable<int> _MorePressed;
		
		private System.Nullable<int> _SeeAllPressed;
		
		private System.Nullable<System.DateTime> _TimeCreated;
		
		private string _MisparIshi;
		
		private string _GivenName;
		
		private string _Source;
		
		private System.Nullable<bool> _Shared;
		
		private EntitySet<Request> _Requests;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(string value);
    partial void OnIDChanged();
    partial void OnRequestsMadeChanging(System.Nullable<int> value);
    partial void OnRequestsMadeChanged();
    partial void OnMailSentChanging(System.Nullable<int> value);
    partial void OnMailSentChanged();
    partial void OnMorePressedChanging(System.Nullable<int> value);
    partial void OnMorePressedChanged();
    partial void OnSeeAllPressedChanging(System.Nullable<int> value);
    partial void OnSeeAllPressedChanged();
    partial void OnTimeCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeCreatedChanged();
    partial void OnMisparIshiChanging(string value);
    partial void OnMisparIshiChanged();
    partial void OnGivenNameChanging(string value);
    partial void OnGivenNameChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnSharedChanging(System.Nullable<bool> value);
    partial void OnSharedChanged();
    #endregion
		
		public Log()
		{
			this._Requests = new EntitySet<Request>(new Action<Request>(this.attach_Requests), new Action<Request>(this.detach_Requests));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="VarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RequestsMade", DbType="Int")]
		public System.Nullable<int> RequestsMade
		{
			get
			{
				return this._RequestsMade;
			}
			set
			{
				if ((this._RequestsMade != value))
				{
					this.OnRequestsMadeChanging(value);
					this.SendPropertyChanging();
					this._RequestsMade = value;
					this.SendPropertyChanged("RequestsMade");
					this.OnRequestsMadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailSent", DbType="Int")]
		public System.Nullable<int> MailSent
		{
			get
			{
				return this._MailSent;
			}
			set
			{
				if ((this._MailSent != value))
				{
					this.OnMailSentChanging(value);
					this.SendPropertyChanging();
					this._MailSent = value;
					this.SendPropertyChanged("MailSent");
					this.OnMailSentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MorePressed", DbType="Int")]
		public System.Nullable<int> MorePressed
		{
			get
			{
				return this._MorePressed;
			}
			set
			{
				if ((this._MorePressed != value))
				{
					this.OnMorePressedChanging(value);
					this.SendPropertyChanging();
					this._MorePressed = value;
					this.SendPropertyChanged("MorePressed");
					this.OnMorePressedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SeeAllPressed", DbType="Int")]
		public System.Nullable<int> SeeAllPressed
		{
			get
			{
				return this._SeeAllPressed;
			}
			set
			{
				if ((this._SeeAllPressed != value))
				{
					this.OnSeeAllPressedChanging(value);
					this.SendPropertyChanging();
					this._SeeAllPressed = value;
					this.SendPropertyChanged("SeeAllPressed");
					this.OnSeeAllPressedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeCreated", DbType="DateTime")]
		public System.Nullable<System.DateTime> TimeCreated
		{
			get
			{
				return this._TimeCreated;
			}
			set
			{
				if ((this._TimeCreated != value))
				{
					this.OnTimeCreatedChanging(value);
					this.SendPropertyChanging();
					this._TimeCreated = value;
					this.SendPropertyChanged("TimeCreated");
					this.OnTimeCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MisparIshi", DbType="VarChar(255)")]
		public string MisparIshi
		{
			get
			{
				return this._MisparIshi;
			}
			set
			{
				if ((this._MisparIshi != value))
				{
					this.OnMisparIshiChanging(value);
					this.SendPropertyChanging();
					this._MisparIshi = value;
					this.SendPropertyChanged("MisparIshi");
					this.OnMisparIshiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GivenName", DbType="VarChar(255)")]
		public string GivenName
		{
			get
			{
				return this._GivenName;
			}
			set
			{
				if ((this._GivenName != value))
				{
					this.OnGivenNameChanging(value);
					this.SendPropertyChanging();
					this._GivenName = value;
					this.SendPropertyChanged("GivenName");
					this.OnGivenNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="VarChar(255)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shared", DbType="Bit")]
		public System.Nullable<bool> Shared
		{
			get
			{
				return this._Shared;
			}
			set
			{
				if ((this._Shared != value))
				{
					this.OnSharedChanging(value);
					this.SendPropertyChanging();
					this._Shared = value;
					this.SendPropertyChanged("Shared");
					this.OnSharedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Log_Request", Storage="_Requests", ThisKey="ID", OtherKey="ID")]
		public EntitySet<Request> Requests
		{
			get
			{
				return this._Requests;
			}
			set
			{
				this._Requests.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Requests(Request entity)
		{
			this.SendPropertyChanging();
			entity.Log = this;
		}
		
		private void detach_Requests(Request entity)
		{
			this.SendPropertyChanging();
			entity.Log = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AdminChanges")]
	public partial class AdminChange : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Description;
		
		private System.DateTime _TimeAdded;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnTimeAddedChanging(System.DateTime value);
    partial void OnTimeAddedChanged();
    #endregion
		
		public AdminChange()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeAdded", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime TimeAdded
		{
			get
			{
				return this._TimeAdded;
			}
			set
			{
				if ((this._TimeAdded != value))
				{
					this.OnTimeAddedChanging(value);
					this.SendPropertyChanging();
					this._TimeAdded = value;
					this.SendPropertyChanged("TimeAdded");
					this.OnTimeAddedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
